version: '3.8'

services:
  # Layanan Backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    # Menambahkan DNS Server publik untuk mengatasi masalah koneksi ke internet
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      # Variabel untuk koneksi internal
      - NEO4J_URI=bolt://neo4j-v5-3:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=12345678
      - OLLAMA_HOST=http://ollama:11434
      # Variabel untuk API Key, diambil dari file .env (LEBIH AMAN)
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - chatbot-net
    restart: unless-stopped

  # Layanan Frontend Streamlit
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: chatbot-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - chatbot-net
    depends_on:
      - backend
    restart: unless-stopped

# Menggunakan jaringan eksternal yang sudah kita siapkan
networks:
  chatbot-net:
    external: true